client/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.client, name='client')
]

conch_music/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from discover import views
from my_music import views as music_views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.do_login, name='login'),
    url(r'^register/$', views.do_register, name='register'),
    url(r'^logout/$', views.do_logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_to_sheet/', music_views.add_to_sheet),
    # url(r'^user/(?P<user_id>\d+)/$', views.user, name='user'),
    url(r'^discover/', include('discover.urls', namespace='discover')),
    url(r'^client/', include('client.urls', namespace='client')),
    url(r'^member/', include('member.urls',namespace='member')),
    url(r'^my_music/', include('my_music.urls', namespace='my_music')),
    url(r'^player/', include('player.urls', namespace='player')),
    url(r'^admin/', admin.site.urls)
]

discover/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^singer/(?P<singer_name>(\w|\.)+$)', views.singer, name='singer'),

    url(r'^singer/(?P<singer_name>\w+$)', views.singer, name='singer'),

]

my_music/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$', views.my_music, name='my_music'),
    url(r'^attention/$', views.attention, name='attention'),
    url(r'^fans/$', views.fans, name='fans'),
    url(r'focus_user/$',views.focus_user, name='focus_user'),
    url(r'my_song_menu/$', views.my_song_menu, name='my_song_menu'),
    url(r'^new_sheet/$', views.new_sheet),
    url(r'^del_sheet/$', views.del_sheet),
    url(r'^del_music/$', views.del_music ),
]

player/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.player, name='player'),
    url(r'^like/$',views.like, name='like'),
    url(r'^like_selected/$', views.like_selected, name='like_selected'),
    url(r'^flush/$', views.flush),
    url(r'^play_singer/$', views.play_singer, name='play_singer'),
]

my_music/views.py
from django.shortcuts import render, render_to_response
from django.http import  HttpResponse
# Create your views here.
from discover.models import *

def my_music(request):
    # music_list
    user_id = request.GET.get('user', False)
    if user_id:
        user = User.objects.filter(user_id=user_id)[0]
    elif request.session.get('user_id',False):
        user_id = request.session['user_id']
        user = User.objects.filter(user_id=user_id)[0]
    else:
        return render(request, 'my_music/my_music.html', {'this_user': None, 'that_user': None })
    sheet_id = request.GET.get('sheet',None)
    if not sheet_id:
        favourite = MusicFavourite.objects.filter(user_id=user_id)
        music_list = []
        for f in range(len(favourite)):
            music_list.append(MusicList.objects.get(list_id=favourite[f].Fmusic_id))
        return render(request, 'my_music/my_music.html', {'that_user': user,
                                                          'this_user': request.session,
                                                          'sheet_name': '喜欢',
                                                          'music_list': music_list})
    else:
        music_sheet_list = MusicSheet.objects.filter(sheet_id=sheet_id)
        music_list = []
        if music_sheet_list:
            for music_sheet in music_sheet_list:
                music_list.append(MusicList.objects.filter(list_id=music_sheet.music_id)[0])
        sheet_name = UserSheet.objects.filter(sheet_id=sheet_id)[0].sheet_name
        return render(request, 'my_music/my_music.html', {'that_user': user,
                                                          'this_user': request.session,
                                                          'sheet_name': sheet_name ,
                                                          'music_list': music_list})


def attention(request, singer_id=None):
    user_id = request.GET.get('user', False)
    if not user_id:
        user_id = request.session.get('user_id', None)
    user = User.objects.filter(user_id=user_id)[0]
    singer_id_list = Friend.objects.filter(user_id = user_id, follow_id__lt=1000000)
    singer_list = []
    for singer_id in singer_id_list:
        singer_list.append(SingerInfo.objects.filter(singer_id=singer_id.follow_id)[0])
    return render(request, 'my_music/focus.html', {'singer_list': singer_list,
                                                   'this_user': request.session,
                                                   'that_user':user})


def focus_user(request):
    user_id = request.GET.get('user', False)
    if not user_id:
        user_id = request.session.get('user_id', None)
    user = User.objects.filter(user_id=user_id)[0]
    user_id_list = Friend.objects.filter(user_id = user_id, follow_id__gt=1000000)
    user_list = []
    for use_id in user_id_list:
        user_list.append(User.objects.filter(user_id = use_id.follow_id)[0])
    return render(request, 'my_music/focus_user.html', {'user_list':user_list,
                                                        'that_user':user,
                                                        'this_user': request.session})


def fans(request):
    user_id = request.GET.get('user', False)
    if not user_id:
        user_id = request.session.get('user_id', None)
    user = User.objects.filter(user_id=user_id)[0]
    fan_id_list= Friend.objects.filter(follow_id=user_id)
    fan_list = []
    for f in fan_id_list:
        fan_list.append(User.objects.filter(user_id=f.user_id)[0])
    return render(request, 'my_music/fans.html', {'list': fan_list,
                                                  'that_user':user,
                                                  'this_user': request.session,})



def my_song_menu(request):
    user_id = request.GET.get('user', False)
    if not user_id:
        user_id = request.session.get('user_id', None)
    user = User.objects.filter(user_id=user_id)[0]
    sheet_list = UserSheet.objects.filter(user_id=user_id)
    like_count = MusicFavourite.objects.filter(user_id=user_id).count()
    return render(request, 'my_music/my_song_menu.html', {'like_count':like_count,
                                                          'sheet_list': sheet_list,
                                                          'that_user':user,
                                                          'this_user': request.session})



def new_sheet(request):
    user_id = request.session.get('user_id', None)
    sheet_name = request.POST.get('sheet_name', None)
    if sheet_name or sheet_name!='null':
        UserSheet.objects.create(sheet_name=sheet_name, user_id=user_id)
    user_list = UserSheet.objects.filter(user_id=user_id)
    return render(request, 'my_music/sheet_list.html', {'sheet_list': user_list})

def del_sheet(request):
    sheet_id = request.POST.get('sheet_id', None)
    user_id = request.session.get('user_id', None)
    if sheet_id:
        UserSheet.objects.filter(sheet_id=sheet_id).delete()
        print('删除成功')
    sheet_list = UserSheet.objects.filter(user_id=user_id)
    return render(request, 'my_music/sheet_list.html', {'sheet_list': sheet_list})


def add_to_sheet(request):
    if request.method == 'GET':
        music_id = request.GET.get('music_id', None)
        user_id = request.session.get('user_id', None)
        if not user_id:
            return HttpResponse('请先登录')
        else:
            sheet_list = UserSheet.objects.filter(user_id=user_id);
            return render_to_response('add_to_sheet.html', {'sheet_list': sheet_list, 'music_id':music_id})
    else:
        music_id = request.POST.get('music_id', None)
        sheet_id = request.POST.get('sheet_id', None)
        if sheet_id and music_id:
            if sheet_id == '0':
                user_id = request.session.get('user_id')
                if user_id and  not MusicFavourite.objects.filter(user_id=user_id, Fmusic_id=music_id):
                    MusicFavourite.objects.create(user_id=user_id, Fmusic_id=music_id)
                return HttpResponse('添加成功')
            elif not MusicSheet.objects.filter(sheet_id=sheet_id, music_id=music_id):
                MusicSheet.objects.create(sheet_id=sheet_id, music_id=music_id)
                sheet = UserSheet.objects.filter(sheet_id=sheet_id)
                sheet_num = sheet[0].sheet_num + 1
                sheet.update(sheet_num=sheet_num)
                return HttpResponse('添加成功')
            return HttpResponse('歌曲已存在')
        else:
            return HttpResponse('收藏失败')

def del_music(request):
    music_id = request.POST.get('music')
    sheet = request.POST.get('sheet')
    music_list = []
    if sheet == '喜欢':
        user_id = request.session.get('user_id')
        MusicFavourite.objects.filter(user_id=user_id,Fmusic_id=music_id).delete()
        favourite_list = MusicFavourite.objects.filter(user_id=user_id)
        for favourite in favourite_list:
            music_list.append(MusicList.objects.filter(list_id=favourite.Fmusic_id)[0])
    else:
        sheet_id = UserSheet.objects.filter(sheet_name=sheet)[0].sheet_id
        MusicSheet.objects.filter(sheet_id=sheet_id, music_id=music_id).delete()
        music_id_list = MusicSheet.objects.filter(sheet_id=sheet_id)
        for music_id in music_id_list:
            music_list.append(MusicList.objects.filter(list_id=music_id.music_id)[0])
    return render_to_response('my_music/music.html', {'music_list': music_list, 'sheet_name': sheet})

my_music/templates/my_music/fans.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/music_list.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/my_music.css'%}" />


{% endblock %}

{#    start mod_profile#}
{% block main %}

<div class="mod_profile" style="">
    <div class="section_inner">
        <div class="profile__cover_link">
            <img src="{% static that_user.image  %}">
        </div>
        <h1 class="profile__tit">
        <span class="profile__name">{{ that_user.user_nickname }}</span>
        </h1>
        <ul class="mod_user_statistic">
            <li class="user_statistic__item">
                <a href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}"><strong>{{ that_user.attention }}</strong><span>关注</span></a>
            </li>
            <li>
                <a href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}"><strong>{{ that_user.Fan }}</strong><span>粉丝</span></a>
            </li>
        </ul>
    </div>
</div>

<div class="song">
    <div class="song_top">
        <a class="my_like my_like_box" href="{% url 'my_music:my_music' %}?user={{ that_user.user_id }}">喜欢</a>
        <a class="my_like my_like_box" href="{% url 'my_music:my_song_menu' %}?user={{ that_user.user_id }}">歌单</a>
        <a class="my_like" href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}">关注</a>
        <a class="my_like" href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}">粉丝</a>
    </div>



    <div class="js_box" id="focus_box" style="display: block;">
        <div class="profile_cont">
        {% if  list %}
            <div class="js_sub" id="focus_singer_box" style="display: block;">
                <div class="mod_singer_list mod_singer_list--fans">
                    <ul class="singer_list__list">
                        {% for user in list %}
                        <li class="singer_list__item">
                            <div class="singer_list__item_box">
                                <a href="{% url 'my_music:my_music' %}?user={{ user.user_id }}" class="singer_list__cover js_singer" hidefocus="true">
                                    <img class="singer_list__pic" src="{% static user.image %}" onerror="this.src=&#39;" alt="张杰">
                                </a>
                                <h3 class="singer_list__title"><a href="" class="js_singer" title="{{ user.user_nickname }}">{{ user.user_nickname }}</a></h3>
                                <p class="singer_list__info">{{ user.Fan }}人关注</p>
                                <div class="singer_list__focus">
                                    <a href="javascript:;" class="mod_btn singer_list__btn_focus js_follow_singer" >
                                        <span class="btn_focus__cont"><i class="mod_btn__icon_yes"></i>已关注</span>

                                    </a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="focus_not_user_fans" style="display: block;" id="focus_user_box">

                    <div class="none_txt_fans">


                        <p>还没有粉丝... </p>

                    </div>

            </div>
        {% endif %}
        </div>
    </div>

</div>
{% endblock %}

my_music/templates/my_music/focus.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/music_list.css' %}">
    <link rel="stylesheet" type="text/css" href='{%  static "css/my_music.css"%}' />


{% endblock %}

{#    start mod_profile#}
{% block main %}

<div class="mod_profile" style="">
    <div class="section_inner">
        <div class="profile__cover_link">
            <img src="{% static that_user.image  %}">
        </div>
        <h1 class="profile__tit">
        <span class="profile__name">{{ that_user.user_nickname }}</span>
        </h1>
        <ul class="mod_user_statistic">
            <li class="user_statistic__item">
                <a href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}"><strong>{{ that_user.attention }}</strong><span>关注</span></a>
            </li>
            <li>
                <a href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}"><strong>{{ that_user.Fan }}</strong><span>粉丝</span></a>
            </li>
        </ul>
    </div>
</div>

<div class="song">
    <div class="song_top">
        <a class="my_like my_like_box" href="{% url 'my_music:my_music' %}?user={{ that_user.user_id }}">喜欢</a>
        <a class="my_like my_like_box" href="{% url 'my_music:my_song_menu' %}?user={{ that_user.user_id }}">歌单</a>
        <a class="my_like" href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}">关注</a>
        <a class="my_like" href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}">粉丝</a>
    </div>



    <div class="js_box" id="focus_box" style="display: block;">
        <div class="mod_tab" role="nav">
            <a class="mod_tab__item mod_tab__current" href="#" >歌手</a>
            <a class="mod_tab__item" href="{% url 'my_music:focus_user' %}?user={{ that_user.user_id }}" >用户</a>
        </div>
        <div class="profile_cont">
            <a href="{% url 'index' %}" class="mod_btn btn_focus_fan js_focus_friends" style="display: block;">
                <i class="mod_btn__icon_new"></i>关注更多歌手
            </a>

        {% if singer_list %}
            <div class="js_sub" id="focus_singer_box" style="display: block;">
                <div class="mod_singer_list mod_singer_list--fans">
                    <ul class="singer_list__list">
                        {% for singer in singer_list %}
                        <li class="singer_list__item">
                            <div class="singer_list__item_box">
                                <a href="{% url 'discover:singer' singer.singer_name %}" class="singer_list__cover js_singer" hidefocus="true">
                                    <img class="singer_list__pic" src="{% static singer.singer_pic %}" onerror="this.src=&#39;" alt="{{ singer.singer_name }}">
                                </a>
                                <h3 class="singer_list__title"><a href="" class="js_singer" title="{{ singer.singer_name }}">{{ singer.singer_name }}</a></h3>
                                <p class="singer_list__info">{{ singer.fanNo }}人关注</p>
                                <div class="singer_list__focus">
                                    <a href="javascript:;" class="mod_btn singer_list__btn_focus js_follow_singer" >

                                        <span class="btn_focus__cont"><i class="mod_btn__icon_yes"></i>已关注</span>

                                    </a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="focus_not_user" style="display: block;" id="focus_user_box">
                    <div class="none_txt">
                        <p>什么也没有，去看看 <a href="{% url 'index' %}" style="color: #00BAC6">热门歌曲!</a> </p>
                    </div>
            </div>
        {% endif %}
        </div>
    </div>

</div>
{% endblock %}

my_music/templates/my_music/focus_user.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/music_list.css' %}">
    <link rel="stylesheet" type="text/css" href='{%  static "css/my_music.css"%}' />


{% endblock %}

{#    start mod_profile#}
{% block main %}

<div class="mod_profile" style="">
    <div class="section_inner">
        <div class="profile__cover_link">
            <img src="{% static that_user.image  %}">
        </div>
        <h1 class="profile__tit">
        <span class="profile__name">{{ that_user.user_nickname }}</span>
        </h1>
        <ul class="mod_user_statistic">
            <li class="user_statistic__item">
                <a href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}"><strong>{{ that_user.attention }}</strong><span>关注</span></a>
            </li>
            <li>
                <a href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}"><strong>{{ that_user.Fan }}</strong><span>粉丝</span></a>
            </li>
        </ul>
    </div>
</div>

<div class="song">
    <div class="song_top">
        <a class="my_like my_like_box" href="{% url 'my_music:my_music' %}?user={{ that_user.user_id }}">喜欢</a>
        <a class="my_like my_like_box" href="{% url 'my_music:my_song_menu' %}?user={{ that_user.user_id }}">歌单</a>
        <a class="my_like" href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}">关注</a>
        <a class="my_like" href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}">粉丝</a>
    </div>

    <div class="js_box" id="focus_box" style="display: block;">
        <div class="mod_tab" role="nav">
            <a class="mod_tab__item mod_tab__current" href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}" >歌手</a>
            <a class="mod_tab__item" href="#" >用户</a>
        </div>
        <div class="profile_cont">
{#            <a href="javascript:;" class="mod_btn btn_focus_fan js_focus_friends" style="display: block;">#}
{#                <i class="mod_btn__icon_new"></i>关注更多歌手#}
{#            </a>#}

        {% if user_list %}
            <div class="js_sub" id="focus_singer_box" style="display: block;">
                <div class="mod_singer_list mod_singer_list--fans">
                    <ul class="singer_list__list">
                        {% for that_user in user_list%}
                        <li class="singer_list__item">
                            <div class="singer_list__item_box">
                                <a href="{% url 'my_music:my_music' %}?user={{ that_user.user_id }}" class="singer_list__cover js_singer" hidefocus="true">
                                    <img class="singer_list__pic" src="{% static that_user.image %}" onerror="this.src=&#39;" alt="{{ that_user.user_nickname }}">
                                </a>
                                <h3 class="singer_list__title"><a href="" class="js_singer" title="{{ that_user.user_nickname }}">{{ that_user.user_nickname }}</a></h3>
                                <p class="singer_list__info">{{ that_user.Fan }}人关注</p>
                                <div class="singer_list__focus">
                                    <a href="javascript:;" class="mod_btn singer_list__btn_focus js_follow_singer" >
                                        <span class="btn_focus__cont"><i class="mod_btn__icon_yes"></i>已关注</span>
                                    </a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="focus_not_user" style="display: block;" id="focus_user_box">
                    <div class="none_txt">
                        <p>什么也没有，快去看看 <a href="{% url 'index' %}" style="color: #00BAC6">热门歌曲!</a> </p>
                    </div>
            </div>
        {% endif %}
        </div>
    </div>

</div>
{% endblock %}

my_music/templates/my_music/my_music.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/music_list.css' %}">
    <link rel="stylesheet" type="text/css" href='{%  static "css/my_music.css"%}' />
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_to_sheet.css' %}">


{% endblock %}

{#    start mod_profile#}
{% block main %}
    {% if that_user.user_id %}
          <div class="mod_profile" style="">
        <div class="section_inner">
            <div class="profile__cover_link">
                <img src="{% static that_user.image  %}">
            </div>
            <h1 class="profile__tit">
            <span class="profile__name">{{ that_user.user_nickname }}</span>
            </h1>
            <ul class="mod_user_statistic">
                <li class="user_statistic__item">
                    <a href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}"><strong>{{ that_user.attention }}</strong><span>关注</span></a>
                </li>
                <li>
                    <a href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}"><strong>{{ that_user.Fan }}</strong><span>粉丝</span></a>
                </li>
            </ul>
        </div>
    </div>

    <div class="song" style="left: 300px">
        <div class="song_top" style="left: 0px">
            <a class="my_like" href="#">{{ sheet_name }}</a>
            <a class="my_like" href="{% url 'my_music:my_song_menu' %}?user={{ that_user.user_id }}">歌单</a>
            <a class="my_like" href="{% url 'my_music:attention' %}?user={{ that_user.user_id }}">关注</a>
            <a class="my_like" href="{% url 'my_music:fans' %}?user={{ that_user.user_id }}">粉丝</a>
        </div>
{#        <div class="like_box">#}
{#            <div class="song_like">#}
{#                <a class="gequ" href="#">歌曲</a>#}
{#                <a class="zhuanji" href="#">专辑</a>#}
{#            </div>#}


            <div class="mod_songlist_toolbar">
                <a href="{% url 'player:player' %}?user={{ that_user.user_id }}&sheet={{ sheet_name }}" class="mod_btn_green js_all_play" target="player_window" ><i class="mod_btn_green__icon_play"></i>播放全部</a>
                <a href="" class="mod_btn js_all_fav" ><i class="mod_btn__icon_add"></i>添加到</a>
                <a href="" class="mod_btn js_all_down" ><i class="mod_btn__icon_down"></i>下载</a>
                <a href="" class="mod_btn js_batch" ><i class="mod_btn__icon_batch"></i>批量操作</a>
            </div>
            <div class="music_list">
                <div class="list_header">
                    <ul>
                        <li class="li_music"><label >歌曲</label></li>
                        <li class="li_singer"><label >歌手</label></li>
                        <li class="li_album"><label >专辑</label></li>
                        <li class="li_time"><label >时长</label></li>
                    </ul>
                </div>
                <div class="list_content">
                    {% for music in music_list %}
                        <div class="rows" data-this_user="{{ this_user.user_id }}" data-that_user="{{ that_user.user_id }}">
                            <ul>
                                <li>
                                    <div class="music_name">
                                        <a class="music_a">{{ music.music_name }}</a>
                                        <div class="download"><a class="download_a" href="{% static music.music_path %}" download="{{ music.music_name }}.mp3"></a></div>
                                        <div class="add"><a class="add_a"></a></div>
                                        <div class="play" data-music_path="{{ music.music_path }}">
                                            <a href="{% url 'player:player' %}?list_id={{ music.list_id }}" class="play_a" target="player_window"></a>
                                        </div>
                                    </div>
                                </li>
                                <li><div class="singer"><label>{{ music.singer }}</label></div></li>
                                <li><div class="album"><a><p>{{ music.music_name | default:'无名'}}</p></a></div></li>
                                <li><div class="time"><label>{{ music.length_time | default:'3:00'}}</label></div></li>
                                <li><div class="single-delete-music" data-sheet="{{ sheet_name }}" data-music_id="{{ music.list_id }}"></div></li>
                            </ul>
                        </div>
                    {% endfor %}
                     <script>
                            let INNERELEMENT = {
                                    rows: '.rows',
                                    linkDownload: '.download_a',
                                    linkAdd: '.add_a',
                                    linkPlay: '.play_a',
                                    addToSheet: '.mod_btn js_all_fav',
                                    singleDeleteMusic: '.single-delete-music',
                                    time: '.time',
                                    singerAddToSheet: '.add',

                                };
                            $(INNERELEMENT.rows).mouseover(function (e) {
                                $(this).find(INNERELEMENT.linkDownload).css('display', 'block');
                                $(this).find(INNERELEMENT.linkAdd).css('display', 'block');
                                $(this).find(INNERELEMENT.linkPlay).css('display', 'block');
                                this_user = $(this).data('this_user');
                                that_user = $(this).data('that_user');
                                if(this_user === that_user){
                                    $(this).find(INNERELEMENT.time).css('display', 'none');
                                    $(this).find(INNERELEMENT.singleDeleteMusic).css('display', 'block');
                                }
                            });

                            $(INNERELEMENT.rows).mouseout(function (e) {
                                $(this).find(INNERELEMENT.linkDownload).css('display', 'none');
                                $(this).find(INNERELEMENT.linkAdd).css('display', 'none');
                                $(this).find(INNERELEMENT.linkPlay).css('display', 'none');
                                $(this).find(INNERELEMENT.time).css('display', 'block');
                                $(this).find(INNERELEMENT.singleDeleteMusic).css('display', 'none');
                            });
                            $(INNERELEMENT.singleDeleteMusic).click(function () {
                                musicId = $(this).data('music_id');
                                sheet_id = $(this).data('sheet');
                                $.post('/my_music/del_music/', {'music': musicId, 'sheet': sheet_id}, function(response, status, xhr) {
                                    $('.list_content').html(response)
                                })
                            })
                     </script>
                    <script type="application/javascript" src="{% static 'js/music-list.js' %}"></script>
                </div>

            </div>
{#        </div>#}
        </div>
        <div class="add-to-sheet">
    </div>
    {% else %}
        <div class="login_bck">
            <div class="login_box">
                <h1 align="center" class="login_bt">私人音乐空间，听我想听的歌</h1>
                <h4 align="center" class="login_me">登录我的音乐</h4>
                <a href="{% url 'login' %}">
                    <button class="login_butt" >立即登录</button>
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}


my_music/templates/my_music/sheet_list.html
{% load static %}
<ul class="playlist_main">
    {% for sheet in sheet_list %}
        <li class="playlist">
            <div class="playlist_cover">
            <a href="{% url 'my_music:my_music' %}?user={{ user.user_id }}&sheet={{ sheet.sheet_id }}"><img src="{% static sheet.sheet_pic %}" alt="我喜欢"></a>
            </div>
            <a href="{% url 'my_music:my_music' %}?user={{ user.user_id }}&sheet={{ sheet.sheet_id }}" class="playlist_my_like">{{ sheet.sheet_name }}</a>
            <span class="playlist_num">{{ sheet.sheet_num }}首</span>
            <div class="del-list-icon" data-sheet_id="{{ sheet.sheet_id }}"></div>
        </li>
    {% endfor %}
<script>
            function del_sheet(){
                let sheet_id = $(this).data('sheet_id');
                let this_user = $(this).data('this_user');
                let that_user = $(this).data('that_user');
                if(that_user === this_user){
                    let signal = window.confirm('确定删除?');
                    if(signal){
                        $.post('/my_music/del_sheet/', {'sheet_id': sheet_id}, function (response, status, xhr) {
                            $('.sheet-list').html(response);
                        })
                    }
                }else{
                    let myWindow = $('.windows');
                    myWindow.find('span').html('只有主人才能创建歌单哦');
                    myWindow.css('display', 'block');
                    setTimeout(function () {
                        myWindow.css('display', 'none');
                    },1000)
                }
            }

            $('.playlist').mouseover(function () {
                $(this).find('.del-list-icon').css('display', 'block')
            });

            $('.playlist').mouseout(function () {
                $(this).find('.del-list-icon').css('display', 'none')
            });

            $('.del-list-icon').click(del_sheet);
        </script>
</ul>