client/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.client, name='client')
]

conch_music/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from discover import views
from my_music import views as music_views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.do_login, name='login'),
    url(r'^register/$', views.do_register, name='register'),
    url(r'^logout/$', views.do_logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_to_sheet/', music_views.add_to_sheet),
    # url(r'^user/(?P<user_id>\d+)/$', views.user, name='user'),
    url(r'^discover/', include('discover.urls', namespace='discover')),
    url(r'^client/', include('client.urls', namespace='client')),
    url(r'^member/', include('member.urls',namespace='member')),
    url(r'^my_music/', include('my_music.urls', namespace='my_music')),
    url(r'^player/', include('player.urls', namespace='player')),
    url(r'^admin/', admin.site.urls)
]

member/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$',views.member, name='member')
]

my_music/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$', views.my_music, name='my_music'),
    url(r'^attention/$', views.attention, name='attention'),
    url(r'^fans/$', views.fans, name='fans'),
    url(r'focus_user/$',views.focus_user, name='focus_user'),
    url(r'my_song_menu/$', views.my_song_menu, name='my_song_menu'),
    url(r'^new_sheet/$', views.new_sheet),
    url(r'^del_sheet/$', views.del_sheet),
    url(r'^del_music/$', views.del_music ),
]

player/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.player, name='player'),
    url(r'^like/$',views.like, name='like'),
    url(r'^like_selected/$', views.like_selected, name='like_selected'),
    url(r'^flush/$', views.flush),
    url(r'^play_singer/$', views.play_singer, name='play_singer'),
]

templates/add_to_sheet.html
<ul>
    <li><a href="{% url 'player:player' %}?list_id={{ music_id }}" target="player_window" class="sheet-list">播放队列</a></li>
    <li><a data-sheet_id="0" class="sheet-list">我喜欢</a></li>
    {% for sheet in sheet_list %}
        <li><a class="sheet-list" data-sheet_id="{{ sheet.sheet_id }}">{{ sheet.sheet_name }}</a></li>
    {% endfor %}
</ul>

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
	<head>
        <title>{% block title %}Base{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link type="images/x-icon" rel="shortcut icon" href="{% static 'images/logo3.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/slider.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/jQuery-carouselFigure.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/myaudio.css' %}">
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        {% block head %}
        {% endblock %}
        <style>
            .login_img{
                margin: 20px 10px 0 0;
                width: 50px;
                height: 50px;
                border: white solid 2px;
                overflow: hidden;
                border-radius: 50%;
            }
            a:hover{
                cursor: pointer ;
            }

        </style>

{#        {% block public_music_list %}#}
{#        {% endblock %}#}

        <!---start-login-script--->
	</head>
    <body>
        <div class="header_bg">
			<div class="wrap">
				<div class="header">
					<div class="logo">
						<a href="{% url 'index' %}" style="float: left ;">
							<img src="{% static 'images/logo4.jpg' %}" width="60px" height="60px" alt="" />
						</a>
					</div>
					<a href="{% url 'index' %}">
						<h3>海螺音乐 </h3></a>
					<!--<div class="social-icons">-->
					<div class="sign-ligin-btns">
						<ul>
							<li id="loginContainer">
								{% if this_user.user_id %}
                                    <a href="{% url 'my_music:my_music' %}" class="login" id="loginLabel" >
                                        <img class="login_img" src="{% static this_user.image %}">
                                    </a>
                                {% else %}
                                    <a class="login" id="loginButton" href="{% url 'login' %}"><span>登录</span></a>
								{% endif %}
                                <div class="clear"></div>
								<!-- Login Ends Here -->
							</li>
							<li id="signupContainer">
								{% if this_user.user_id %}
                                    <a class="signup" id="signupButton" href="{% url 'logout' %}"><span>注销</span></a>
                                {% else %}
                                    <a class="signup" id="signupButton" href="{% url 'register' %}"><span>注册</span></a>
                                {% endif %}
								<div class="clear"> </div>
								<!-- Login Ends Here -->
							</li>
{#							<div class="clear"> </div>#}
						</ul>
					</div>
					<div class="clear"> </div>
				</div>
				<div class="clear"> </div>
			</div>
			<div class="clear"></div>
		</div>
		<!-- start header -->

		<div class="header_btm">
			<div class="wrap">
				<div class="header_sub">
					<div class="h_menu">
						<ul>
							<li class="active">
								<a href="{% url 'index' %}">发现</a>
							</li>
							<li>
								<a href="{% url 'my_music:my_music' %}">我的音乐</a>
							</li>
							<li>
								<a href="{% url 'client:client' %}">客户端</a>
							</li>
							<li>
                                <a href="https://uland.taobao.com/sem/tbsearch?refpid=mm_26632258_3504122_32538762&clk1=09fc198b3e4407582d87b834bea2e066&keyword=%E8%80%B3%E6%9C%BA&page=0">商城</a>
							</li>
							<li>
								<a href="{% url 'member:member' %}">VIP</a>
							</li>
						</ul>
					</div>
					<div class="h_search">
						<form action="{% url 'search' %}" method="get" >
							<input type="text" name="search" placeholder="search music" required="required">
							<input type="submit" value="">
						</form>
					</div>
					<div class="sub-head">
						<ul>
							<li>
								<a href="#" id="menu">Menu <span></span></a>
							</li>
							<li>
								<a href="#" id="search">Search <span></span></a>
							</li>
						</ul>
						<div class="clear"></div>
					</div>
					<script type="text/javascript">
						$(".menu,.search").hide();
						$("#menu").click(function() {
							$(".menu").toggle();
							$(".search").hide();
							$("#search").removeClass("active");
							$("#menu").toggleClass("active");
						});
						$("#search").click(function() {
							$(".search").toggle();
							$(".menu").hide();
							$("#menu").removeClass("active");
							$("#search").toggleClass("active");
							$(".text").focus();
						});
					</script>
					<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
					<div class="clear"></div>

					<div class="clear"></div>
				</div>
			</div>
		</div>

        {% block main %}
{#        <!--      在这里重写自己的内容    >#}

        {% endblock %}
        <div class="footer_bg">
			<div class="wrap">
				<div class="footer">
					<!-- start span_of_4 -->
					<div class="span_of_4">
						<div class="span1_of_4">
							<h4>开发过程</h4>
							<p>通过不断地开发，每个小组成员所负责的部分已经设计完成和部分已经实现</p>
							<ul class="f_nav1">
								<li class="timer">
									<a href="#">9-october 2018 </a>
								</li>
							</ul>
							<p class="top">未开发完,待定</p>
							<ul class="f_nav1">
								<li class="timer">
									<a href="#">9-october 2018 </a>
								</li>
							</ul>
						</div>
						<div class="span1_of_4">
							<h4>介绍</h4>
							<p>整体主要采用html css js技术来实现，html来实现静态页面，css对静态页面进行修饰，用javascript来实现轮播图，登陆，注册，播放进度条等，未完待续！</p>
						</div>
						<div class="span1_of_4">
							<h4>关于我们</h4>
							<p class="btm">这是一个优秀的团队出产的作品，每一个成员都起到了不可替代的作用</p>
							<p>由于开发时间的限制，有的部分还不太完美，后续的部分将会逐渐完善</p>

						</div>
						<div class="span1_of_4">
							<h4>保持联系</h4>
							<p class="btm">我们的公司一直欢迎合作伙伴的加盟,同时也欢迎有实力，有志向的伙伴加入我们</p>
							<p class="btm1 pin">北京市大兴区</p>
							<p class="btm1 mail">
								<a href="mailto:info@mycompany.com">公司邮箱</a>
							</p>
							<p class="call">01234 444 777</p>
						</div>
						<div class="clear"></div>
					</div>
				</div>
			</div>
		</div>
		<!-- start footer -->
		<div class="footer_bg1">
			<div class="wrap">
				<div class="footer1">
					<!-- scroll_top_btn -->
					<a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
					<!--end scroll_top_btn -->

					<div class="footer2">
						<p align="center" style="color: darkgray;">
							<a href="http://www.tencent.com/" rel="noopener nofollow" target="_blank" title="关于吴彦组">关于吴彦组</a> |
							<a href="http://www.tencent.com/index_e.shtml" rel="noopener nofollow" target="_blank" title="About Tencent">About Tencent</a> |
							<a href="http://www.qq.com/contract.shtml" rel="noopener nofollow" target="_blank" title="服务条款">服务条款</a> |
							<a href="http://y.qq.com/y/static/tips/service_tips.html" rel="noopener nofollow" target="_blank" title="用户服务协议">用户服务协议</a> |
							<a href="https://y.qq.com/m/client/intro/privacy.html" rel="noopener nofollow" target="_blank" title="隐私政策">隐私政策</a> |
							<a href="https://y.qq.com/vip/right_declare/index.html" rel="noopener nofollow" target="_blank" title="权利声明">权利声明</a> |
							<a href="http://www.tencentmind.com/" rel="noopener nofollow " target="_blank " title="广告服务 ">广告服务</a> |
								<a href="http://hr.tencent.com/ " rel="noopener nofollow " target="_blank " title="吴彦组招聘 ">吴彦组招聘</a> |
								<a href="http://service.qq.com/ " rel="noopener nofollow " target="_blank " title="客服中心 ">客服中心</a> |
								<a href="http://www.qq.com/map/ " rel="noopener nofollow " target="_blank " title="网站导航 ">网站导航</a>
							</p>
                            <p align="center " style="color: grey;padding: auto;text-align: center ">Copyright © 1998 - <script type="text/javascript ">document.write(new Date().getFullYear());</script>2018 Tencent.
                            	<a target="_blank " href="http://www.tencent.com/en-us/le/copyrightstatement.shtml " rel="noopener nofollow " title="All Rights Reserved. ">All Rights Reserved.</a></p>
	                        <p align="center " style="color: darkgrey;padding: auto;text-align: center ">吴彦组公司 <a  target="_blank " href="http://www.tencent.com/zh-cn/le/copyrightstatement.shtml " rel="noopener nofollow " title="版权所有 ">
                            <p align="center " style="color: grey;padding: auto; ">Copyright © 1998 - <script type="text/javascript ">document.write(new Date().getFullYear());</script>2018 Tencent.
                            	<a target="_blank " href="http://www.tencent.com/en-us/le/copyrightstatement.shtml " rel="noopener nofollow " title="All Rights Reserved. ">All Rights Reserved.</a></p>
	                        <p align="center " style="color: darkgrey;padding: auto; ">吴彦组公司 <a  target="_blank " href="http://www.tencent.com/zh-cn/le/copyrightstatement.shtml " rel="noopener nofollow " title="版权所有 ">
	                        	版权所有</a> <a target="_blank " href="http://www.tencent.com/law/mo_law.shtml?/law/copyright.htm " rel="noopener nofollow " title="吴彦祖文化经营许可证 ">吴彦组文化经营许可证</a></p>
					</div>
					<div class="clear "></div>
                    <div class="windows">
                        <span>弹出窗口</span>
                    </div>
				</div>
			</div>
		</div>
    </body>
</html>

templates/music_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    歌曲列表
{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/music_list.css' %}">
    <link rel="stylesheet" type="text/css" href='{%  static "css/my_music.css"%}' />
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_to_sheet.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.11.3.js' %}"></script>
    {% block head_music_list %}
        <style>
            .select{

            }
            .select li{
                position: absolute;
                left: 100px;
                right: 100px;
                display: none;
            }
        </style>
    {% endblock %}
{% endblock %}




{% block main %}
    {% block private_music_list %}
    {% endblock %}
    <div class="music_list">
        <div class="mod_songlist_toolbar">
            <a href="{% url 'player:play_singer' %}?singer={{ singer.singer_name }}" class="mod_btn_green js_all_play" target="player_window" ><i class="mod_btn_green__icon_play"></i>播放全部</a>
            <a href="#" class="mod_btn js_all_fav" ><i class="mod_btn__icon_add"></i>添加到</a>
            <a href="#" class="mod_btn js_all_down" ><i class="mod_btn__icon_down"></i>下载</a>
            <a href="#" class="mod_btn js_batch" ><i class="mod_btn__icon_batch"></i>批量操作</a>
        </div>
        <div class="list_header">
            <ul class="select">
                <li class="li_music"><label >歌曲</label></li>
                <li class="li_singer"><label >歌手</label></li>
                <li class="li_album"><label >专辑</label></li>
                <li class="li_time"><label >时长</label></li>
            </ul>
        </div>
        <div class="list_content">
            {% for music in music_list %}
                <div class="rows">
                    <ul>
                        <li>
                            <div class="music_name">
                                <div class="select-music"></div>
                                <a class="music_a">{{ music.music_name }}</a>
                                <div class="download"><a class="download_a" href="{% static music.music_path %}" download="{{ music.music_name }}.mp3"></a></div>
                                <div class="add" data-music_id="{{ music.list_id }}"><a class="add_a"></a></div>
                                <div class="play" data-music_path="{{ music.music_path }}">
                                    <a href="{% url 'player:player' %}?list_id={{ music.list_id }}" class="play_a" target="player_window"></a>
                                </div>
                            </div>
                        </li>
                        <li><div class="singer"><label>{{ music.singer }}</label></div></li>
                        <li><div class="album"><a><p>{{ music.music_name | default:'无名'}}</p></a></div></li>
                        <li><div class="time"><label>{{ music.length_time | default:'3:00'}}</label></div></li>
                    </ul>
                </div>
            {% endfor %}
            <div class="mod_page_nav"><strong class="current">1</strong>
                <a href="" class="js_pageindex" data-index="2" hidefocus="">2</a>
                <a href="" class="js_pageindex" data-index="3" hidefocus="">3</a>
                <a href="" class="js_pageindex" data-index="4" hidefocus="">4</a><strong class="more">...</strong>
                <a href="" class="js_pageindex" data-index="19" hidefocus="">19</a>
                <a href="" class="next js_pageindex" data-index="2" title="下一页" hidefocus=""><span>&gt;</span></a>
            </div>
        </div>
    </div>
    <div class="add-to-sheet">
    </div>
    <script>
        let ELEMENT = {
            rows: '.rows',
            linkDownload: '.download_a',
            linkAdd: '.add_a',
            linkPlay: '.play_a',
            addToSheet: '.mod_btn js_all_fav',
            singleDeleteMusic: '.single-delete-music',
            time: '.time',
        };
        $(ELEMENT.rows).mouseover(function (e) {
            $(this).find(ELEMENT.linkDownload).css('display', 'block');
            $(this).find(ELEMENT.linkAdd).css('display', 'block');
            $(this).find(ELEMENT.linkPlay).css('display', 'block');
        });

        $(ELEMENT.rows).mouseout(function (e) {
            $(this).find(ELEMENT.linkDownload).css('display', 'none');
            $(this).find(ELEMENT.linkAdd).css('display', 'none');
            $(this).find(ELEMENT.linkPlay).css('display', 'none');
        });
    </script>
    <script type="text/javascript" src="{% static 'js/music-list.js' %}"></script>
{% endblock %}